In [256]:
import numpy as np
import pandas as pd

In [257]:
# df = pd.read_csv("../../data/real_estate.csv")
df = pd.read_csv("mlr.csv")
df.sample(5)

R&D Spend  Administration  Marketing Spend       State     Profit
48     542.05        51743.15             0.00    New York   35673.41
27   72107.60       127864.55        353183.81    New York  105008.31
2   153441.51       101145.55        407934.54     Florida  191050.39
25   64664.71       139553.16        137962.62  California  107404.34
14  119943.24       156547.42        256512.92     Florida  132602.65

In [258]:
df = df.drop(['State'], axis=1)
df.sample(5)

R&D Spend  Administration  Marketing Spend     Profit
7   130298.13       145530.06        323876.68  155752.60
34   46426.07       157693.92        210797.67   96712.80
6   134615.46       147198.87        127716.82  156122.51
2   153441.51       101145.55        407934.54  191050.39
36   28663.76       127056.21        201126.82   90708.19

In [259]:
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()

# df = scaler.fit_transform(df)

In [260]:
# import seaborn as sns

# sns.pairplot(df)

In [261]:
# x = df.iloc[:, :-1]
# y = df.iloc[:, -1]
from sklearn.datasets import load_diabetes

x,y = load_diabetes(return_X_y=True)

print(x.shape)
print(y.shape)

(442, 10)
(442,)


In [262]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(353, 10)
(353,)
(89, 10)
(89,)


In [263]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(xtrain, ytrain)

LinearRegression()

In [264]:
ypred = reg.predict(xtrain)

In [265]:
from sklearn.metrics import root_mean_squared_error, r2_score

print('r2', r2_score(ytrain, ypred))
print('rmse', root_mean_squared_error(ytrain, ypred))

r2 0.5153742608928653
rmse 53.578988435389746


In [266]:
reg.coef_

array([ -74.5131216 , -262.95460495,  542.20787683,  348.85953333,
       -769.07621151,  465.55204861,  105.34465801,  174.50648571,
        763.56166387,    2.78297297])

In [267]:
reg.intercept_

149.44261347746402

###

In [268]:
epochs = 1000
lr = 0.1
c = 0
ms = np.ones(x.shape[1])

for i in range(epochs):

    y_hat = np.dot(xtrain, ms) + c
    cslope = -2 * np.mean(ytrain - y_hat)
    stepsize = lr * cslope
    # print(c)
    c -= stepsize

    mslope = -2 * np.dot(ytrain - y_hat, xtrain)/xtrain.shape[0] 
    ms -= lr * mslope

In [269]:
ms

array([  31.11470676,  -39.14809167,  272.54755136,  171.49687165,
         37.3165352 ,   12.77572131, -146.22586322,  130.52903373,
        224.89215179,  111.21745711])

In [270]:
c

150.37184332537763

In [271]:
ypred = []
for xt in xtest:
    ypred.append(np.dot(xt, ms) + c)

In [272]:
r2_score(ytest, ypred)

0.45387676962255297

In [298]:

epochs = 1000
lr = 0.1
c = 0
ms = np.ones(x.shape[1])

for i in range(epochs):
    for j in range(xtrain.shape[0]):
        idx = np.random.randint(0, xtrain.shape[0])

        y_hat = np.dot(xtrain[idx], ms) + c
        cslope = -2 * (ytrain[idx] - y_hat)
        stepsize = lr * cslope
        # print(c)
        c -= stepsize

        mslope = -2 * np.dot(ytrain[idx] - y_hat, xtrain[idx])
        ms -= lr * mslope

In [299]:
ms

array([ -71.39780462, -237.35944978,  548.93778296,  324.28512501,
       -610.3158271 ,  310.56991109,    9.23336186,  176.62580305,
        693.29833453,  -15.36727436])

In [300]:
c

166.72114167576873

In [301]:
ypred = []
for xt in xtest:
    ypred.append(np.dot(xt, ms) + c)

In [302]:
r2_score(ytest, ypred)

0.5280034393120412

In [311]:
epochs = 1000
lr = 0.1
c = 0
batch_size = 64
ms = np.ones(x.shape[1])

for i in range(epochs):

    x_batch = []
    y_batch = []

    for i in range(int(xtrain.shape[0]//batch_size)):
        idx = np.random.randint(0, xtrain.shape[0])
        x_batch.append(xtrain[idx])
        y_batch.append(ytrain[idx])

    y_hat = np.dot(x_batch, ms) + c
    cslope = -2 * np.mean(y_batch - y_hat)
    stepsize = lr * cslope
    # print(c)
    c -= stepsize

    mslope = -2 * np.dot(y_batch - y_hat, x_batch)/len(x_batch) 
    ms -= lr * mslope

In [312]:
ms

array([  31.07171089,  -55.21352132,  274.21424385,  162.59378758,
         37.6526259 ,   14.75233895, -145.82241044,  131.48403836,
        221.63666871,  107.08879076])

In [313]:
ypred = []
for xt in xtest:
    ypred.append(np.dot(xt, ms) + c)

In [314]:
r2_score(ytest, ypred)

0.45948668158395145